server:
  port: 8081

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud01?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qiyuewu1
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

eureka:
  client:
    #不向配置中心配置自己
    register-with-eureka: true
    #表示自己是服务中心,不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    # 注册到服务中心的名字,如果不想显示 spring.application.name的值 就手动配一个
    instance-id: payment8001
    # 鼠标 移动到服务名称时,浏览器左下角显示ip地址
    prefer-ip-address: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 别名
  # type-aliases-package:
